---
- hosts: all
  remote_user: pi
  tasks:
  - name: Set authorized key took from file
    authorized_key:
      user: pi
      state: present
      key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
  - name: Install awscli
    apt: pkg=awscli state=latest
    sudo: yes
